title: Me, in Website Form
name: DSC180A-Methodology-5
theme: just-the-docs/just-the-docs@v0.4.0.rc3

url: https://github.com/zaki1503/Zaki-Ahmed

aux_links: 
  My Github: https://github.com/zaki1503
  My LinkedIn: https://www.linkedin.com/in/zakisahmed/