title: Me, in Website Form
name: DSC180A-Methodology-5
theme: jekyll-theme-minimal

url: https://github.com/zaki1503/Zaki-Ahmed

aux_links: 
  My Github: https://github.com/zaki1503
  My LinkedIn: https://www.linkedin.com/in/zakisahmed/